### ISSUE TITLE
"in JavaScript even a number is an object!"

### ISSUE THREAD

**Issue by eltoroit** [Moddable-OpenSource/iot-product-dev-book#13]
Thanks for writing this awesome book and the SDK!

On page #38, in the section titled "Converting Numbers to Strings", the first paragraph says "yes, in JavaScript even a number is an object!" but I believe that it should probably say "yes, in JavaScript even a number can be treated as an object!".

The example you show for this illustrates the point. The variable `a` is a primitive number, not an instance of the Number class, which would be initialized as `let a = new Number(1);`

The next line uses the variable `a` as an instance of the class Number because JavaScript automatically converts it using a term called "boxing".

**Comment by phoddie** [comment]
> Thanks for writing this awesome book and the SDK!

Thank you!

> The variable a is a primitive number, not an instance of the Number class

Correct. You already understand a fairly advanced topic. The goal of Chapter 2 is to get C and C++ programmers working with JavaScript quickly and painlessly. Primitives and boxing are unnecessary for that goal, and something of a distraction. One of the great things about JavaScript is that developers don't need to know about these details to make effective use of the language. But it is necessary to understand that the language allows numbers (and some other primitives, notably strings) to support methods invocation (e.g. `Number.prototype.toString`).
