### ISSUE TITLE
Error with code 3-21: Server can't be closed

### ISSUE THREAD

**Issue by eltoroit** [Moddable-OpenSource/iot-product-dev-book#15]
I am testing listing 3-21 and I'm hitting these errors when the request is not a PUT request: (BTW, It works fine when it's a PUT request): 

- `C:\js4IoT\moddable\modules\network\http\http.js (611) # Break: server: no function!` on [this line](https://github.com/Moddable-OpenSource/moddable/blob/3458406d8c63783019e58d03de9e2a7055f1983c/modules/network/http/http.js#L611) 
- `C:\js4IoT\moddable\modules\network\http\http.js (756) # Break: server: no function!` on [this line](https://github.com/Moddable-OpenSource/moddable/blob/3458406d8c63783019e58d03de9e2a7055f1983c/modules/network/http/http.js#L756)
- `C:\js4IoT\moddable\modules\network\http\http.js (759) # Break: server: cannot coerce undefined to object!` on [this line](https://github.com/Moddable-OpenSource/moddable/blob/3458406d8c63783019e58d03de9e2a7055f1983c/modules/network/http/http.js#L759)
- `XS abort: unhandled exception`
- `C:\js4IoT\moddable\xs\platforms\esp\xsPlatform.c (235) # Break: C: xsDebugger!` on [this line](https://github.com/Moddable-OpenSource/moddable/blob/3458406d8c63783019e58d03de9e2a7055f1983c/xs/platforms/esp/xsPlatform.c#L235)
- and then the board resets!

I believe the problem is with [this line](https://github.com/Moddable-OpenSource/iot-product-dev-book/blob/ed82cdaad805913371d88cd7d402a4c8a0ab9a2a/ch3-network/http-server-put/example.js#L23) where `this` (meaning the request) is closed.

If I do not close the request, then there is no error :-)

**Comment by phoddie** [comment]
Thanks for the report. There are a couple lines missing from the http server implementation. I have that fixed locally as part of a pending patch. You can make the change easily until that's available. The `Server.status` callback is invoked at [line 591](https://github.com/Moddable-OpenSource/moddable/blob/3458406d8c63783019e58d03de9e2a7055f1983c/modules/network/http/http.js#L591). After that, add these two lines:

```js
	if (!this.socket)
		return;
```

**Comment by eltoroit** [comment]
I made that change, and the problem went away. Thanks for the quick turnaround.

**Comment by phoddie** [comment]
Excellent. Glad that helped. Thanks for confirming.
