### ISSUE TITLE
Type in code page 243. 

### ISSUE THREAD

**Issue by eltoroit** [Moddable-OpenSource/iot-product-dev-book#16]
Page 243 has this code

```
let r1 = new Resource("myData.dat");
let values = new Uint16Array(r1.slice(32, 10, false));
```

But slide uses start and end positions, not stop and offset, therefore `values` always will be undefined. Please consider changing the code to 

```
let r1 = new Resource("myData.dat");
let values = new Uint16Array(r1.slice(32, 32 + 10, false));
```

**Comment by phoddie** [comment]
Good catch. The [corrigendum](https://github.com/Moddable-OpenSource/iot-product-dev-book/blob/master/corrigendum.md) has been updated.
