### ISSUE TITLE
Ch1 helloworld-gui - screen is undefined

### ISSUE THREAD

**Issue by KevinBatdorf** [Moddable-OpenSource/iot-product-dev-book#19]
**Build environment:** macOS

**Target device:** NodeMCU ESP32 Devkit ([amazon](https://www.amazon.com/dp/B07Q576VWZ))

**Description**

I'm going through chapter 1 and wired up the display on the ESP32. I'm attempting to run the `helloworld-gui` example.

Previously I ran `mcconfig -d -m -p esp32/nodemcu` from the ch1 hosts directory (not sure that's important). Then following the instructions I ran it again from the helloworld-gui directory.

It opened up the debugger and errored on `screen`

> helloworld-gui/main.js (20) # Break: ?: get screen: undefined variable!

**Images**

![Screen Shot 2022-08-07 at 7 52 27 PM](https://user-images.githubusercontent.com/1478421/183315992-b0d237ab-3fd1-4eb0-9196-bfbebbe9c552.png)

**Other information**

Relevant code: https://github.com/Moddable-OpenSource/iot-product-dev-book/blob/master/ch1-gettingstarted/helloworld-gui/main.js#L20

I'm assuming `screen` is a global that should be defined, and I'm missing a module? 

The devkit esp32 has different pins but I found a pinout sheet online and used that. I double checked but I could have made an error with that as well.

Thanks

**Comment by phoddie** [comment]
The `screen` global is only present for platforms that have a display. The `esp32/nodemcu` has no screen, it is just a bare module. Some ESP32 platforms that have a display are: `esp32/moddable_two`, `esp32/m5stack`, `esp32/m5stack_fire`, `esp32/heltec_wifi_kit_32`, and `esp32/m5stick_c`. There's a good list available [here](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/esp32.md#platforms-esp32).

If you have wired a display to your ESP32 NodeMCU board following the instructions on Page 19, then you can use the `esp32/moddable_zero` target as noted near the bottom of page 22.

**Comment by KevinBatdorf** [comment]
I missed that, thanks. And I confirm it's working properly using that target. Thanks for the fast reply.

**Comment by phoddie** [comment]
Cool. Glad you got it working. I usually get the wiring wrong on my first three attempts. ;)

**Comment by KevinBatdorf** [comment]
Yeah no joke. Me too normally ha ha. Somehow got lucky with that this time :)
