### ISSUE TITLE
[Bug] Wrong equality operator in "http-get-json" example

### ISSUE THREAD

**Issue by nickthiru** [Moddable-OpenSource/iot-product-dev-book#21]
**Build environment:** Windows

**Target device:** NodeMCU ESP32

**Description**

In "ch3-network\http-get-json\example.js", on line 29, the equality operator should be "===" and not "==".

**Images**

![image](https://user-images.githubusercontent.com/47299208/219830289-15fec0f7-adbe-4e22-8825-56532898b04a.png)

**Comment by phoddie** [comment]
Thanks for the report. The code was working, but not following best practices. That's been fixed in this example and a few others.

**Comment by nickthiru** [comment]
Noted. I was getting an error with "==". I spotted it when I compared this book example with the example in Moddable, which used "===" and worked.
